
version: '3'
services:
  strapi:
    container_name: strapi
    build: 
      context: .
      dockerfile: ./Dockerfile.prod
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: '.tmp/data.db'
      JWT_SECRET: 'WOkyfMaqPI5ADMWVsXALOA=='
      ADMIN_JWT_SECRET: 'YqWwyHnrShPLd14g9GvO1g=='
      APP_KEYS: 'tr1x3Tyj3Khywypl0AzKAA==,Cvzl+lLkR7S7sjwNP3tiJQ==,HI0B0CUjdueXW6kMj5clGQ==,E86h8ymQYxIDR5kFwvzViA=='
      # NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge